### ISSUE TITLE
Action runner failing to build due to `GLIBC_2.27' not found

### ISSUE THREAD

**Issue by wreiske** [mieweb/docs#28]
https://github.com/mieweb/docs/actions/runs/9960797572
```
Post job cleanup.
/home/docsqa/actions-runner-public/externals/node[2](https://github.com/mieweb/docs/actions/runs/9960797572/job/27520857825#step:20:2)0/bin/node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /home/docsqa/actions-runner-public/externals/node20/bin/node)
/home/docsqa/actions-runner-public/externals/node20/bin/node: /lib64/libstdc++.so.6: version `GLIBCXX_[3](https://github.com/mieweb/docs/actions/runs/9960797572/job/27520857825#step:20:3).4.20' not found (required by /home/docsqa/actions-runner-public/externals/node20/bin/node)
/home/docsqa/actions-runner-public/externals/node20/bin/node: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/docsqa/actions-runner-public/externals/node20/bin/node)
/home/docsqa/actions-runner-public/externals/node20/bin/node: /lib6[4](https://github.com/mieweb/docs/actions/runs/9960797572/job/27520857825#step:20:4)/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/docsqa/actions-runner-public/externals/node20/bin/node)
/home/docsqa/actions-runner-public/externals/node20/bin/node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /home/docsqa/actions-runner-public/externals/node20/bin/node)
/home/docsqa/actions-runner-public/externals/node20/bin/node: /lib64/libc.so.6: version `GLIBC_2.2[5](https://github.com/mieweb/docs/actions/runs/9960797572/job/27520857825#step:20:5)' not found (required by /home/docsqa/actions-runner-public/externals/node20/bin/node)
```

**Comment by wreiske** [comment]
https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

Removal of Operating System support for non-Node20 OS versions
To support this change, we will be removing the Action runner support for the following operating systems which do not have official support for Node20:
– Red Hat Enterprise Linux 7
– CentOS 7
– Oracle Linux 7
– Debian 9
– Ubuntu 16.04
– Linux Mint 18
– openSUSE 15
– SUSE Enterprise Linux (SLES) 12 SP2
– Windows 7 64-bit
– Windows 8.1 64-bit

**Comment by ggodlewski** [comment]
Yeah, we've done fix for that in wikigdrive last week.

**Comment by monpie3** [comment]
Unfortunately, the fix that worked for `wikigdrive` did not work here. It might be necessary to upgrade the Node version or update the OS version.

Similar issue: https://github.com/nvm-sh/nvm/issues/2972

**Comment by ggodlewski** [comment]
Chat by Will:
"I am working on fixing it. The server it runs on is super old. It would be cool to think about how we can "host" different wikigdrive websites, like "[webchartnow.wikigdrive.com](http://webchartnow.wikigdrive.com/)" for the webchart docs, and "[enterprisehealth.wikigdrive.com](http://enterprisehealth.wikigdrive.com/)" since it's all static, we could just push everything to cloudflare pages or similar and be able to scale it easily. Can use custom CNAMES for [docs.webchartnow.com](http://docs.webchartnow.com/) that actually points to [webchartnow.wikigdrive.com](http://webchartnow.wikigdrive.com/) where we host it and charge for storage / build time (like how github actions is billed, s3 storage, etc...)"

**Comment by horner** [comment]
will rebuilt the docs-qa server
